# Generated by Django 2.2.17 on 2020-12-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_jhgjhg"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="jkjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
