# Generated by Django 2.2.17 on 2020-12-31 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_jkjh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='jhgjhg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='jkjh',
        ),
    ]
